class ScriptStatus:

    DRAFT = "DRAFT"

    SCRIPT_GENERATED = "SCRIPT_GENERATED"

    SCENES_GENERATED = "SCENES_GENERATED"

    IMAGES_GENERATED = "IMAGES_GENERATED"

    AUDIOS_GENERATED = "AUDIOS_GENERATED"

    VIDEOS_GENERATED = "VIDEOS_GENERATED"

    COMPLETED = "COMPLETED"

    FAILED = "FAILED"