"""Upgrade User Model

Revision ID: 2f995b6e6796
Revises: b9b04b236fc6
Create Date: 2026-06-29 02:26:52.458857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f995b6e6796'
down_revision: Union[str, Sequence[str], None] = 'b9b04b236fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Projects', sa.Column('CreatedBy', sa.Integer(), nullable=True))
    op.add_column('Projects', sa.Column('UpdatedBy', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('PublicId', sa.String(length=36), nullable=False))
    op.add_column('Users', sa.Column('Username', sa.String(length=50), nullable=False))
    op.add_column('Users', sa.Column('ProfileImage', sa.String(length=500), nullable=True))
    op.add_column('Users', sa.Column('Role', sa.String(length=50), nullable=False))
    op.add_column('Users', sa.Column('CreatedBy', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('UpdatedBy', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_PublicId'), 'Users', ['PublicId'], unique=True)
    op.create_index(op.f('ix_Users_Username'), 'Users', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_Username'), table_name='Users')
    op.drop_index(op.f('ix_Users_PublicId'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_column('Users', 'UpdatedBy')
    op.drop_column('Users', 'CreatedBy')
    op.drop_column('Users', 'Role')
    op.drop_column('Users', 'ProfileImage')
    op.drop_column('Users', 'Username')
    op.drop_column('Users', 'PublicId')
    op.drop_column('Projects', 'UpdatedBy')
    op.drop_column('Projects', 'CreatedBy')
    # ### end Alembic commands ###
