"""Initial database

Revision ID: b9b04b236fc6
Revises: 
Create Date: 2026-06-29 01:45:56.584454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b04b236fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Projects',
    sa.Column('ProjectId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('ProjectName', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(length=1000), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], ),
    sa.PrimaryKeyConstraint('ProjectId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Projects')
    op.drop_table('Users')
    # ### end Alembic commands ###
